#pragma once

#define AUDIO_ALGO_VERSION_MAJOR 0
#define AUDIO_ALGO_VERSION_MINOR 2
#define AUDIO_ALGO_VERSION_REVISION 0

#define AUDIOALGOAUX_STR_EXP(__A) #__A
#define AUDIOALGOAUX_STR(__A) AUDIOALGOAUX_STR_EXP(__A)

#define AUDIO_ALGO_VERSION \
    AUDIOALGOAUX_STR(AUDIO_ALGO_VERSION_MAJOR) \
    "." AUDIOALGOAUX_STR(AUDIO_ALGO_VERSION_MINOR) "." AUDIOALGOAUX_STR(AUDIO_ALGO_VERSION_REVISION)

extern const char g_AUDIO_ALGO_SHA1[];
